import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-b from-tbp via-purple-500 to-tbp min-h-screen'>{children}</body>
    </html>
  )
}
